name: almoterfy
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.0
  carousel_slider: ^5.1.1
  share_plus: ^10.1.2
  page_transition: ^2.1.0
  blurrycontainer: ^1.0.2
  # skeletons: ^0.0.3
  skeletonizer: ^2.1.0+1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  substring_highlight: ^1.0.33
  sqflite: ^2.3.0
  path: ^1.8.3
  lottie: ^2.6.0
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
  flutter_local_notifications: ^18.0.1
  flutter_html: ^3.0.0-beta.2
  liquid_pull_to_refresh: ^3.0.1
  package_info_plus: ^8.1.1
  flutter_email_sender: ^6.0.2
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.1.14
  webview_flutter: ^4.4.4
  flutter_svg: ^2.2.2
  google_api_availability: ^5.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/lunchericon/appicon.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Assets/images/
    - Assets/animations/
    - Assets/svgs/
    - Assets/fill/
    - Assets/badrDB.sqlite

  fonts:
    - family: Jazeera-Regular
      fonts:
        - asset: ./Assets/fonts/dijlah-reg.ttf

    - family: Jazeera-Bold
      fonts:
        - asset: ./Assets/fonts/dijfont-bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
